TEMP_PATH = "temp"
EXTRACTED_AUTH_PATH = f"{TEMP_PATH}/extracted_audio.wav"
EXPORT_PATH = "export"
ENHENCED_AUTH_PATH = f"{TEMP_PATH}/audio_enhenced.wav"
VIDEO_GENERATION_PATH = f"{TEMP_PATH}/video_generation"